### ISSUE TITLE
placetype= argument is being ignored by whosonfirst.places.getNearby

### ISSUE THREAD

**Issue by simonw** [whosonfirst/whosonfirst-www-api#64] opened 2017-08-02 20:07 UTC
The placetype= argument is documented here: https://mapzen.com/documentation/wof/methods/#whosonfirst.places.getNearby

This API call:

https://whosonfirst-api.mapzen.com/?api_key=mapzen-xxx&method=whosonfirst.places.getNearby&extras=geom:&latitude=40.7128&longitude=-74.0059&placetype=locality

Returns this JSON - which includes places with a placetype that isn't locality. This is a regression - until very recently this API call was doing the right thing.

    {
        "places": [
            {
                "wof:id": 404528709,
                "wof:parent_id": "-1",
                "wof:name": "North Atlantic Ocean",
                "wof:placetype": "ocean",
                "wof:country": "",
                "wof:repo": "whosonfirst-data",
                "geom:longitude": -35.348262,
                "geom:area": 3120.90514,
                "geom:type": "Polygon",
                "geom:bbox": "-81.5206257799,0.0222728540002,6.55704715336,68.4371666531",
                "geom:latitude": 31.978187,
                "geom:area_square_m": "3.11281217052e+13"
            },
            {
                "wof:id": 85633793,
                "wof:parent_id": "102191575",
                "wof:name": "United States",
                "wof:placetype": "country",
                "wof:country": "US",
                "wof:repo": "whosonfirst-data",
                "geom:longitude": -113.2686,
                "geom:area_square_m": "9.8166849609e+12",
                "geom:type": "MultiPolygon",
                "geom:area": 1166.187278,
                "geom:bbox": "-179.231086,18.86546,179.859681,71.441059",
                "geom:latitude": 45.964509
            },
            {
                "wof:id": 102191575,
                "wof:parent_id": "-1",
                "wof:name": "North America",
                "wof:placetype": "continent",
                "wof:country": "",
                "wof:repo": "whosonfirst-data",
                "geom:longitude": -92.335587,
                "geom:type": "MultiPolygon",
                "geom:bbox": "-179.143503,5.515082,179.780935,83.634101",
                "geom:latitude": 56.498698,
                "geom:area_square_m": "2.41799415723e+13",
                "geom:area": 3704.177719
            },
            {
                "wof:id": 0,
                "wof:parent_id": "-1",
                "wof:name": "Earth",
                "wof:placetype": "planet",
                "wof:country": "",
                "wof:repo": "whosonfirst-data",
                "geom:longitude": 0,
                "geom:type": "Polygon",
                "geom:area": 64800,
                "geom:bbox": "-180.0,-90.0,180.0,90.0",
                "geom:latitude": 0
            },
            {
                "wof:id": 102047399,
                "wof:parent_id": "85633793",
                "wof:name": "America/New_York",
                "wof:placetype": "timezone",
                "wof:country": "",
                "wof:repo": "whosonfirst-data",
                "geom:longitude": -78.848444,
                "geom:latitude": 37.951913,
                "geom:type": "MultiPolygon",
                "geom:area": 136.1151,
                "geom:bbox": "-86.489334,19.894085,-66.954811,47.458649"
            },
            {
                "wof:id": 85688543,
                "wof:parent_id": "85633793",
                "wof:name": "New York",
                "wof:placetype": "region",
                "wof:country": "US",
                "wof:repo": "whosonfirst-data",
                "geom:longitude": -75.596537,
                "geom:latitude": 42.921227,
                "geom:type": "MultiPolygon",
                "geom:area": 15.580769,
                "geom:bbox": "-79.76259,40.477399,-71.777491,45.015865"
            },
            {
                "wof:id": 1108746619,
                "wof:parent_id": "85633793",
                "wof:name": "New York",
                "wof:placetype": "constituency",
                "wof:country": "US",
                "wof:repo": "whosonfirst-data-constituency-us",
                "geom:longitude": -75.596537,
                "geom:type": "MultiPolygon",
                "geom:area": 15.580769,
                "geom:bbox": "-79.76259,40.477399,-71.777491,45.015865",
                "geom:area_square_m": "1.41061372408e+11",
                "geom:latitude": 42.921227
            },
            {
                "wof:id": 85977539,
                "wof:parent_id": "-4",
                "wof:name": "New York",
                "wof:placetype": "locality",
                "wof:country": "US",
                "wof:repo": "whosonfirst-data",
                "geom:longitude": -73.930463,
                "geom:type": "MultiPolygon",
                "geom:bbox": "-74.2555913632,40.4961339876,-73.7000090639,40.915532777",
                "geom:latitude": 40.694457,
                "geom:area_square_m": "783424470.067",
                "geom:area": 0.083563
            },
            {
                "wof:id": 102081863,
                "wof:parent_id": "85688543",
                "wof:name": "New York",
                "wof:placetype": "county",
                "wof:country": "US",
                "wof:repo": "whosonfirst-data",
                "geom:bbox": "-74.047285,40.679548,-73.907,40.882214",
                "geom:longitude": -73.96981,
                "geom:latitude": 40.774275,
                "geom:type": "MultiPolygon",
                "geom:area": 0.00928
            },
            {
                "wof:id": 404522731,
                "wof:parent_id": "102081863",
                "wof:name": "Manhattan",
                "wof:placetype": "localadmin",
                "wof:country": "US",
                "wof:repo": "whosonfirst-data",
                "geom:longitude": -73.968861,
                "geom:latitude": 40.775695,
                "geom:type": "MultiPolygon",
                "geom:area": 0.00909,
                "geom:bbox": "-74.0473131531,40.679573,-73.907,40.8820749648",
                "geom:area_square_m": "85115312.955"
            },
            {
                "wof:id": 421205771,
                "wof:parent_id": "85977539",
                "wof:name": "Manhattan",
                "wof:placetype": "borough",
                "wof:country": "US",
                "wof:repo": "whosonfirst-data",
                "geom:longitude": -73.967045,
                "geom:type": "MultiPolygon",
                "geom:bbox": "-74.047729627,40.6829169454,-73.9066509954,40.8790380468",
                "geom:latitude": 40.777595,
                "geom:area": 0.006288,
                "geom:area_square_m": "58882639.6551"
            },
            {
                "wof:id": 1108771513,
                "wof:parent_id": "85688543",
                "wof:name": "New York State Senate District 26",
                "wof:placetype": "constituency",
                "wof:country": "us",
                "wof:repo": "whosonfirst-data-constituency-us-ny",
                "geom:longitude": -73.994285,
                "geom:area": 0.002673,
                "geom:type": "MultiPolygon",
                "geom:bbox": "-74.04728,40.67744,-73.94022,40.73275",
                "geom:latitude": 40.707051,
                "geom:area_square_m": "25053509.211"
            },
            {
                "wof:id": 1108771265,
                "wof:parent_id": "85688543",
                "wof:name": "New York Assembly District 65",
                "wof:placetype": "constituency",
                "wof:country": "us",
                "wof:repo": "whosonfirst-data-constituency-us-ny",
                "geom:longitude": -74.007414,
                "geom:area": 0.001311,
                "geom:type": "MultiPolygon",
                "geom:bbox": "-74.04728,40.67955,-73.97279,40.725448",
                "geom:latitude": 40.703422,
                "geom:area_square_m": "12291544.217"
            },
            {
                "wof:id": 1108738231,
                "wof:parent_id": "85688543",
                "wof:name": "New York Congressional District 10",
                "wof:placetype": "constituency",
                "wof:country": "us",
                "wof:repo": "whosonfirst-data-constituency-us",
                "geom:longitude": -74.001278,
                "geom:area": 0.006351,
                "geom:type": "MultiPolygon",
                "geom:bbox": "-74.053229,40.590982,-73.955275,40.81626",
                "geom:latitude": 40.697617,
                "geom:area_square_m": "59540381.3181"
            },
            {
                "wof:id": 1108738079,
                "wof:parent_id": "85688543",
                "wof:name": "New York Congressional District 7",
                "wof:placetype": "constituency",
                "wof:country": "us",
                "wof:repo": "whosonfirst-data-constituency-us",
                "geom:longitude": -73.948714,
                "geom:area": 0.004739,
                "geom:type": "Polygon",
                "geom:bbox": "-74.025724,40.628644,-73.841046,40.728475",
                "geom:latitude": 40.688456,
                "geom:area_square_m": "44429973.5052"
            },
            {
                "wof:id": 571768561,
                "wof:parent_id": "85865569",
                "wof:name": "City of New York",
                "wof:placetype": "venue",
                "wof:country": "US",
                "wof:repo": "whosonfirst-data-venue-us-ny",
                "geom:bbox": "-74.00588,40.712418,-74.00588,40.712418",
                "geom:longitude": -74.00588,
                "geom:type": "Point",
                "geom:area": 0,
                "geom:latitude": 40.712418,
                "geom:area_square_m": "0.0"
            },
            {
                "wof:id": null,
                "wof:parent_id": null,
                "wof:name": null,
                "wof:placetype": null,
                "wof:country": null,
                "wof:repo": null
            },
            {
                "wof:id": null,
                "wof:parent_id": null,
                "wof:name": null,
                "wof:placetype": null,
                "wof:country": null,
                "wof:repo": null
            },
            {
                "wof:id": null,
                "wof:parent_id": null,
                "wof:name": null,
                "wof:placetype": null,
                "wof:country": null,
                "wof:repo": null
            },
            {
                "wof:id": null,
                "wof:parent_id": null,
                "wof:name": null,
                "wof:placetype": null,
                "wof:country": null,
                "wof:repo": null
            },
            {
                "wof:id": 370837013,
                "wof:parent_id": "85865569",
                "wof:name": "Hirsch Construction Corp",
                "wof:placetype": "venue",
                "wof:country": "US",
                "wof:repo": "whosonfirst-data-venue-us-ny",
                "geom:bbox": "-74.005358,40.712151,-74.005358,40.712151",
                "geom:longitude": -74.005358,
                "geom:type": "Point",
                "geom:area": 0,
                "geom:latitude": 40.712151,
                "geom:area_square_m": "0.0"
            },
            {
                "wof:id": null,
                "wof:parent_id": null,
                "wof:name": null,
                "wof:placetype": null,
                "wof:country": null,
                "wof:repo": null
            },
            {
                "wof:id": null,
                "wof:parent_id": null,
                "wof:name": null,
                "wof:placetype": null,
                "wof:country": null,
                "wof:repo": null
            },
            {
                "wof:id": null,
                "wof:parent_id": null,
                "wof:name": null,
                "wof:placetype": null,
                "wof:country": null,
                "wof:repo": null
            },
            {
                "wof:id": 85867071,
                "wof:parent_id": "421205771",
                "wof:name": "City Hall Area",
                "wof:placetype": "neighbourhood",
                "wof:country": "US",
                "wof:repo": "whosonfirst-data",
                "geom:longitude": -74.00727,
                "geom:type": "Polygon",
                "geom:area": 2.8e-05,
                "geom:bbox": "-74.0110429871,40.7087510142,-74.0036359558,40.7151750338",
                "geom:latitude": 40.712245,
                "geom:area_square_m": "261823.218623"
            },
            {
                "wof:id": 555542119,
                "wof:parent_id": "85865569",
                "wof:name": "Educational Housing",
                "wof:placetype": "venue",
                "wof:country": "US",
                "wof:repo": "whosonfirst-data-venue-us-ny",
                "geom:bbox": "-74.005358,40.712151,-74.005358,40.712151",
                "geom:longitude": -74.005358,
                "geom:type": "Point",
                "geom:area": 0,
                "geom:latitude": 40.712151,
                "geom:area_square_m": "0.0"
            },
            {
                "wof:id": 554779353,
                "wof:parent_id": "85977539",
                "wof:name": "10038",
                "wof:placetype": "postalcode",
                "wof:country": "US",
                "wof:repo": "whosonfirst-data-postalcode-us",
                "geom:longitude": -74.002564,
                "geom:type": "Polygon",
                "geom:area": 8.3e-05,
                "geom:bbox": "-74.010542,40.701689,-73.991777,40.714451",
                "geom:latitude": 40.709308,
                "geom:area_square_m": "775449.706311"
            },
            {
                "wof:id": 85865569,
                "wof:parent_id": "907196817",
                "wof:name": "City Hall Area",
                "wof:placetype": "neighbourhood",
                "wof:country": "US",
                "wof:repo": "whosonfirst-data",
                "geom:longitude": -74.002849,
                "geom:type": "Polygon",
                "geom:bbox": "-74.008614,40.71123,-73.99777,40.717449",
                "geom:latitude": 40.71387,
                "geom:area_square_m": "330955.46179",
                "geom:area": 3.5e-05
            },
            {
                "wof:id": 572185399,
                "wof:parent_id": "85865569",
                "wof:name": "Fast Company",
                "wof:placetype": "venue",
                "wof:country": "US",
                "wof:repo": "whosonfirst-data-venue-us-ny",
                "geom:bbox": "-74.004806,40.712463,-74.004806,40.712463",
                "geom:longitude": -74.004806,
                "geom:type": "Point",
                "geom:area": 0,
                "geom:latitude": 40.712463,
                "geom:area_square_m": "0.0"
            },
            {
                "wof:id": 554779289,
                "wof:parent_id": "85977539",
                "wof:name": "10007",
                "wof:placetype": "postalcode",
                "wof:country": "US",
                "wof:repo": "whosonfirst-data-postalcode-us",
                "geom:longitude": -74.007771,
                "geom:type": "Polygon",
                "geom:area": 4.4e-05,
                "geom:bbox": "-74.013597,40.709806,-74.000455,40.717114",
                "geom:latitude": 40.713858,
                "geom:area_square_m": "412216.414772"
            },
            {
                "wof:id": 907196817,
                "wof:parent_id": "421205771",
                "wof:name": "Downtown",
                "wof:placetype": "macrohood",
                "wof:country": "US",
                "wof:repo": "whosonfirst-data",
                "geom:longitude": -73.997422,
                "geom:type": "MultiPolygon",
                "geom:bbox": "-74.0193425462,40.6997741659,-73.9716294606,40.7425088323",
                "geom:latitude": 40.72077,
                "geom:area": 0.001167,
                "geom:area_square_m": "10932571.5624"
            },
            {
                "wof:id": 1108771267,
                "wof:parent_id": "85688543",
                "wof:name": "New York Assembly District 66",
                "wof:placetype": "constituency",
                "wof:country": "us",
                "wof:repo": "whosonfirst-data-constituency-us-ny",
                "geom:longitude": -74.00549,
                "geom:area": 0.000729,
                "geom:type": "Polygon",
                "geom:bbox": "-74.02152,40.710166,-73.983077,40.74467",
                "geom:latitude": 40.728516,
                "geom:area_square_m": "6833506.63708"
            },
            {
                "wof:id": 85892921,
                "wof:parent_id": "421205771",
                "wof:name": "City Hall",
                "wof:placetype": "neighbourhood",
                "wof:country": "US",
                "wof:repo": "whosonfirst-data",
                "geom:longitude": -74.004,
                "geom:type": "Polygon",
                "geom:area": 1.7e-05,
                "geom:bbox": "-74.0073394775,40.7132570694,-74.000889388,40.7170785158",
                "geom:latitude": 40.715383,
                "geom:area_square_m": "156004.917063"
            },
            {
                "wof:id": 85865711,
                "wof:parent_id": "907196817",
                "wof:name": "Financial District",
                "wof:placetype": "neighbourhood",
                "wof:country": "US",
                "wof:repo": "whosonfirst-data",
                "geom:longitude": -74.009181,
                "geom:type": "Polygon",
                "geom:bbox": "-74.016542,40.6997741659,-73.9991022492,40.71369",
                "geom:latitude": 40.706995,
                "geom:area_square_m": "1265593.56217",
                "geom:area": 0.000135
            },
            {
                "wof:id": null,
                "wof:parent_id": null,
                "wof:name": null,
                "wof:placetype": null,
                "wof:country": null,
                "wof:repo": null
            }
        ],
        "next_query": null,
        "total": null,
        "page": null,
        "per_page": 100,
        "pages": null,
        "cursor": null,
        "stat": "ok"
    }

**Comment by dphiffer** [comment] 2017-08-02 20:43
Thanks @simonw, I'm able to replicate this on our dev machine and I found the cause. Fix coming shortly.

**Comment by thisisaaronland** [comment] 2017-08-02 21:07
Ooops. Sorry... that was my bad.

**Comment by dphiffer** [comment] 2017-08-02 21:10
Ok, this should be fixed now!

**Closed as completed by dphiffer** 2017-08-02 21:10 UTC
